<a href="https://colab.research.google.com/github/AlexeyZazulinskiy/Py8/blob/main/python10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

| Задание 44 |
| --- |
| В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

In [6]:
import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)

In [63]:
data = pd.DataFrame(lst)
data.head()

       0
0  human
1  robot
2  robot
3  human
4  human

In [28]:
pd.get_dummies(data)

    0_human  0_robot
0         1        0
1         0        1
2         0        1
3         1        0
4         1        0
5         1        0
6         0        1
7         1        0
8         0        1
9         0        1
10        1        0
11        0        1
12        1        0
13        1        0
14        1        0
15        0        1
16        0        1
17        0        1
18        1        0
19        0        1

In [64]:
robot = data[data == 'robot'] 
human = data[data == 'human']
pd.concat([human, robot], axis=1)

        0      0
0   human    NaN
1     NaN  robot
2     NaN  robot
3   human    NaN
4   human    NaN
5   human    NaN
6     NaN  robot
7   human    NaN
8     NaN  robot
9     NaN  robot
10  human    NaN
11    NaN  robot
12  human    NaN
13  human    NaN
14  human    NaN
15    NaN  robot
16    NaN  robot
17    NaN  robot
18  human    NaN
19    NaN  robot